SELECT VORNAME, NACHNAME
FROM KUNDE
WHERE VORNAME LIKE 'A%'
  AND ANREDE = 'Frau'

SELECT *
FROM ARTIKEL
WHERE LOWER(ARTIKELNAME) LIKE '%saft'

SELECT *
FROM KUNDE
         LEFT JOIN test t on KUNDE.NACHNAME = t.Nachname
WHERE ORT LIKE 'Maieskuel%'
  AND (EXTRACT(YEAR FROM GEBURTSDATUM) < (EXTRACT(YEAR FROM SYSDATE) - 35))

CREATE VIEW test
AS
SELECT Nachname
FROM Kunde
WHERE FLOOR((SYSDATE - Geburtsdatum) / 365) > 35;

SELECT *
FROM KUNDE
WHERE ORT NOT LIKE '%Maieskuel%'
  AND EXTRACT(YEAR FROM GEBURTSDATUM) > (EXTRACT(YEAR FROM SYSDATE) - 35)
ORDER BY NACHNAME DESC

SELECT NACHNAME
FROM Kunde
WHERE FLOOR((SYSDATE - Geburtsdatum) / 365) < 35
MINUS
SELECT Nachname
FROM Kunde
WHERE UPPER(ort) LIKE '%MAIESKUEL%'
ORDER BY Nachname DESC;


SELECT COUNT(KUNDENNUMMER)
FROM KUNDE
WHERE NACHNAME LIKE 'M%'

SELECT COUNT(*)
FROM BESTELLUNG
WHERE BESTELLDATUM BETWEEN '20.07.2016' AND NEXT_DAY('20.7.2016', 'SONNTAG')

SELECT ARTIKELNAME
FROM ARTIKEL
WHERE PREIS = (SELECT MIN(Preis) FROM Artikel)