SELECT CONCAT(CONCAT(TRIM(VORNAME), ' '), NACHNAME) AS Kunde
FROM KUNDE
WHERE KUNDENNUMMER IN (SELECT BESTELLUNG.KUNDENNUMMER FROM BESTELLUNG WHERE BESTELLNUMMER IN (SELECT BESTELLNUMMER FROM BESTELLPOSITION WHERE ARTIKELNUMMER = 4))

SELECT CONCAT(CONCAT(TRIM(VORNAME), ' '), NACHNAME) AS Kunde
FROM KUNDE k INNER JOIN BESTELLUNG b ON k.KUNDENNUMMER = b.KUNDENNUMMER INNER JOIN BESTELLPOSITION bs ON b.BESTELLNUMMER = bs.BESTELLNUMMER
WHERE bs.ARTIKELNUMMER = 4

SELECT VORNAME, NACHNAME, ARTIKELNAME
FROM LIEFERER l LEFT JOIN LIEFERER_HAS_ARTIKEL la ON l.LIEFERERNUMMER = la.LIEFERERNUMMER LEFT JOIN ARTIKEL a ON la.ARTIKELNUMMER = a.ARTIKELNUMMER
ORDER BY ARTIKELNAME

SELECT VORNAME, NACHNAME
FROM LIEFERER l
WHERE l.LIEFERERNUMMER IN (SELECT LIEFERERNUMMER FROM LIEFERER_HAS_ARTIKEL WHERE ARTIKELNUMMER IN (SELECT ARTIKELNUMMER FROM ARTIKEL))

SELECT (SELECT VORNAME FROM LIEFERER l WHERE l.LIEFERERNUMMER IN (SELECT lha.LIEFERERNUMMER FROM LIEFERER_HAS_ARTIKEL lha WHERE lha.ARTIKELNUMMER = a.ARTIKELNUMMER)) AS Vorname,
       (SELECT NACHNAME FROM LIEFERER l WHERE l.LIEFERERNUMMER IN (SELECT lha.LIEFERERNUMMER FROM LIEFERER_HAS_ARTIKEL lha WHERE lha.ARTIKELNUMMER = a.ARTIKELNUMMER)) AS Nachname,
       ARTIKELNAME
FROM ARTIKEL a
WHERE a.ARTIKELNUMMER IN (
                        SELECT lha.ARTIKELNUMMER
                        FROM LIEFERER_HAS_ARTIKEL lha)
ORDER BY ARTIKELNAME ASC

SELECT DISTINCT VORNAME, NACHNAME, ARTIKELNAME
FROM KUNDE k INNER JOIN BESTELLUNG b ON k.KUNDENNUMMER = b.KUNDENNUMMER INNER JOIN BESTELLPOSITION bs ON b.BESTELLNUMMER = bs.BESTELLNUMMER INNER JOIN Artikel a ON bs.ARTIKELNUMMER = a.ARTIKELNUMMER
ORDER BY ARTIKELNAME ASC

