    (SELECT NACHNAME
    FROM KUNDE
    WHERE ORT = 'Maieskuel'  AND FLOOR((SYSDATE-GEBURTSDATUM)/365) > 35)
MINUS
    (SELECT NACHNAME
     FROM KUNDE
     WHERE UPPER(STRASSE) LIKE UPPER('Am Markt%'))
ORDER BY NACHNAME DESC

SELECT BEZEICHNUNG, KATEGORIEKRZ, OBERKATEGORIE
FROM ARTIKELKATEGORIE
START WITH KATEGORIEKRZ='MIL'
CONNECT BY PRIOR KATEGORIEKRZ = OBERKATEGORIE